/*
 * generated by Xtext 2.13.0
 */
package uibk.ac.at.qe.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uibk.ac.at.qe.dsl.parser.antlr.internal.InternalGameParser;
import uibk.ac.at.qe.dsl.services.GameGrammarAccess;

public class GameParser extends AbstractAntlrParser {

	@Inject
	private GameGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGameParser createParser(XtextTokenStream stream) {
		return new InternalGameParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Game";
	}

	public GameGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GameGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
