/*
 * generated by Xtext 2.13.0
 */
package uibk.ac.at.qe.dsl.oscilloscope.ide


/**
 * Use this class to register ide components.
 */
class OscilloscopeIdeModule extends AbstractOscilloscopeIdeModule {
}
