/**
 * generated by Xtext 2.13.0
 */
package uibk.ac.at.qe.dsl.ui.contentassist;

import uibk.ac.at.qe.dsl.ui.contentassist.AbstractGameProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class GameProposalProvider extends AbstractGameProposalProvider {
}
