/**
 * generated by Xtext 2.13.0
 */
package uibk.ac.at.qe.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import uibk.ac.at.qe.dsl.ui.AbstractGameUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GameUiModule extends AbstractGameUiModule {
  public GameUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
