/**
 * generated by Xtext 2.13.0
 */
package uibk.ac.at.qe.dsl;

import uibk.ac.at.qe.dsl.GameStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GameStandaloneSetup extends GameStandaloneSetupGenerated {
  public static void doSetup() {
    new GameStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
