/**
 * generated by Xtext 2.13.0
 */
package uibk.ac.at.qe.dsl.game;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Game</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uibk.ac.at.qe.dsl.game.Game#getScenes <em>Scenes</em>}</li>
 * </ul>
 *
 * @see uibk.ac.at.qe.dsl.game.GamePackage#getGame()
 * @model
 * @generated
 */
public interface Game extends EObject
{
  /**
   * Returns the value of the '<em><b>Scenes</b></em>' containment reference list.
   * The list contents are of type {@link uibk.ac.at.qe.dsl.game.Scene}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Scenes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scenes</em>' containment reference list.
   * @see uibk.ac.at.qe.dsl.game.GamePackage#getGame_Scenes()
   * @model containment="true"
   * @generated
   */
  EList<Scene> getScenes();

} // Game
