/**
 * generated by Xtext 2.13.0
 */
package uibk.ac.at.qe.dsl.game;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uibk.ac.at.qe.dsl.game.GameFactory
 * @model kind="package"
 * @generated
 */
public interface GamePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "game";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uibk/at/qe/dsl/Game";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "game";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GamePackage eINSTANCE = uibk.ac.at.qe.dsl.game.impl.GamePackageImpl.init();

  /**
   * The meta object id for the '{@link uibk.ac.at.qe.dsl.game.impl.GameImpl <em>Game</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.qe.dsl.game.impl.GameImpl
   * @see uibk.ac.at.qe.dsl.game.impl.GamePackageImpl#getGame()
   * @generated
   */
  int GAME = 0;

  /**
   * The feature id for the '<em><b>Scenes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__SCENES = 0;

  /**
   * The number of structural features of the '<em>Game</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uibk.ac.at.qe.dsl.game.impl.SceneImpl <em>Scene</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.qe.dsl.game.impl.SceneImpl
   * @see uibk.ac.at.qe.dsl.game.impl.GamePackageImpl#getScene()
   * @generated
   */
  int SCENE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENE__NAME = 0;

  /**
   * The feature id for the '<em><b>Declartions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENE__DECLARTIONS = 1;

  /**
   * The feature id for the '<em><b>Definitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENE__DEFINITIONS = 2;

  /**
   * The feature id for the '<em><b>Start Level</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENE__START_LEVEL = 3;

  /**
   * The feature id for the '<em><b>Final Level</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENE__FINAL_LEVEL = 4;

  /**
   * The number of structural features of the '<em>Scene</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link uibk.ac.at.qe.dsl.game.impl.LevelDeclarationImpl <em>Level Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.qe.dsl.game.impl.LevelDeclarationImpl
   * @see uibk.ac.at.qe.dsl.game.impl.GamePackageImpl#getLevelDeclaration()
   * @generated
   */
  int LEVEL_DECLARATION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL_DECLARATION__NAME = 0;

  /**
   * The number of structural features of the '<em>Level Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL_DECLARATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uibk.ac.at.qe.dsl.game.impl.LevelDefinitionImpl <em>Level Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.qe.dsl.game.impl.LevelDefinitionImpl
   * @see uibk.ac.at.qe.dsl.game.impl.GamePackageImpl#getLevelDefinition()
   * @generated
   */
  int LEVEL_DEFINITION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL_DEFINITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL_DEFINITION__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Persons</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL_DEFINITION__PERSONS = 2;

  /**
   * The feature id for the '<em><b>Objects</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL_DEFINITION__OBJECTS = 3;

  /**
   * The feature id for the '<em><b>Next</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL_DEFINITION__NEXT = 4;

  /**
   * The number of structural features of the '<em>Level Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL_DEFINITION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link uibk.ac.at.qe.dsl.game.impl.DescriptionImpl <em>Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.qe.dsl.game.impl.DescriptionImpl
   * @see uibk.ac.at.qe.dsl.game.impl.GamePackageImpl#getDescription()
   * @generated
   */
  int DESCRIPTION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__NAME = 0;

  /**
   * The number of structural features of the '<em>Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uibk.ac.at.qe.dsl.game.impl.PersonImpl <em>Person</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.qe.dsl.game.impl.PersonImpl
   * @see uibk.ac.at.qe.dsl.game.impl.GamePackageImpl#getPerson()
   * @generated
   */
  int PERSON = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__TYPE = 1;

  /**
   * The feature id for the '<em><b>Response</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__RESPONSE = 2;

  /**
   * The feature id for the '<em><b>Position</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__POSITION = 3;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__ACTION = 4;

  /**
   * The feature id for the '<em><b>Objects</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__OBJECTS = 5;

  /**
   * The feature id for the '<em><b>Final Object</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__FINAL_OBJECT = 6;

  /**
   * The number of structural features of the '<em>Person</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link uibk.ac.at.qe.dsl.game.impl.Person_OImpl <em>Person O</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.qe.dsl.game.impl.Person_OImpl
   * @see uibk.ac.at.qe.dsl.game.impl.GamePackageImpl#getPerson_O()
   * @generated
   */
  int PERSON_O = 6;

  /**
   * The feature id for the '<em><b>Items</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_O__ITEMS = 0;

  /**
   * The number of structural features of the '<em>Person O</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_O_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uibk.ac.at.qe.dsl.game.impl.ObjectImpl <em>Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.qe.dsl.game.impl.ObjectImpl
   * @see uibk.ac.at.qe.dsl.game.impl.GamePackageImpl#getObject()
   * @generated
   */
  int OBJECT = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__TYPE = 1;

  /**
   * The feature id for the '<em><b>Response</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__RESPONSE = 2;

  /**
   * The feature id for the '<em><b>Position</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__POSITION = 3;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__ACTION = 4;

  /**
   * The number of structural features of the '<em>Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link uibk.ac.at.qe.dsl.game.Action_O <em>Action O</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.qe.dsl.game.Action_O
   * @see uibk.ac.at.qe.dsl.game.impl.GamePackageImpl#getAction_O()
   * @generated
   */
  int ACTION_O = 8;

  /**
   * The meta object id for the '{@link uibk.ac.at.qe.dsl.game.Action_P <em>Action P</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.qe.dsl.game.Action_P
   * @see uibk.ac.at.qe.dsl.game.impl.GamePackageImpl#getAction_P()
   * @generated
   */
  int ACTION_P = 9;


  /**
   * Returns the meta object for class '{@link uibk.ac.at.qe.dsl.game.Game <em>Game</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game</em>'.
   * @see uibk.ac.at.qe.dsl.game.Game
   * @generated
   */
  EClass getGame();

  /**
   * Returns the meta object for the containment reference list '{@link uibk.ac.at.qe.dsl.game.Game#getScenes <em>Scenes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Scenes</em>'.
   * @see uibk.ac.at.qe.dsl.game.Game#getScenes()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Scenes();

  /**
   * Returns the meta object for class '{@link uibk.ac.at.qe.dsl.game.Scene <em>Scene</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scene</em>'.
   * @see uibk.ac.at.qe.dsl.game.Scene
   * @generated
   */
  EClass getScene();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.qe.dsl.game.Scene#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uibk.ac.at.qe.dsl.game.Scene#getName()
   * @see #getScene()
   * @generated
   */
  EAttribute getScene_Name();

  /**
   * Returns the meta object for the containment reference list '{@link uibk.ac.at.qe.dsl.game.Scene#getDeclartions <em>Declartions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declartions</em>'.
   * @see uibk.ac.at.qe.dsl.game.Scene#getDeclartions()
   * @see #getScene()
   * @generated
   */
  EReference getScene_Declartions();

  /**
   * Returns the meta object for the containment reference list '{@link uibk.ac.at.qe.dsl.game.Scene#getDefinitions <em>Definitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Definitions</em>'.
   * @see uibk.ac.at.qe.dsl.game.Scene#getDefinitions()
   * @see #getScene()
   * @generated
   */
  EReference getScene_Definitions();

  /**
   * Returns the meta object for the reference '{@link uibk.ac.at.qe.dsl.game.Scene#getStartLevel <em>Start Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Start Level</em>'.
   * @see uibk.ac.at.qe.dsl.game.Scene#getStartLevel()
   * @see #getScene()
   * @generated
   */
  EReference getScene_StartLevel();

  /**
   * Returns the meta object for the reference '{@link uibk.ac.at.qe.dsl.game.Scene#getFinalLevel <em>Final Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Final Level</em>'.
   * @see uibk.ac.at.qe.dsl.game.Scene#getFinalLevel()
   * @see #getScene()
   * @generated
   */
  EReference getScene_FinalLevel();

  /**
   * Returns the meta object for class '{@link uibk.ac.at.qe.dsl.game.LevelDeclaration <em>Level Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Level Declaration</em>'.
   * @see uibk.ac.at.qe.dsl.game.LevelDeclaration
   * @generated
   */
  EClass getLevelDeclaration();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.qe.dsl.game.LevelDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uibk.ac.at.qe.dsl.game.LevelDeclaration#getName()
   * @see #getLevelDeclaration()
   * @generated
   */
  EAttribute getLevelDeclaration_Name();

  /**
   * Returns the meta object for class '{@link uibk.ac.at.qe.dsl.game.LevelDefinition <em>Level Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Level Definition</em>'.
   * @see uibk.ac.at.qe.dsl.game.LevelDefinition
   * @generated
   */
  EClass getLevelDefinition();

  /**
   * Returns the meta object for the reference '{@link uibk.ac.at.qe.dsl.game.LevelDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see uibk.ac.at.qe.dsl.game.LevelDefinition#getName()
   * @see #getLevelDefinition()
   * @generated
   */
  EReference getLevelDefinition_Name();

  /**
   * Returns the meta object for the containment reference '{@link uibk.ac.at.qe.dsl.game.LevelDefinition#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see uibk.ac.at.qe.dsl.game.LevelDefinition#getDescription()
   * @see #getLevelDefinition()
   * @generated
   */
  EReference getLevelDefinition_Description();

  /**
   * Returns the meta object for the containment reference list '{@link uibk.ac.at.qe.dsl.game.LevelDefinition#getPersons <em>Persons</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Persons</em>'.
   * @see uibk.ac.at.qe.dsl.game.LevelDefinition#getPersons()
   * @see #getLevelDefinition()
   * @generated
   */
  EReference getLevelDefinition_Persons();

  /**
   * Returns the meta object for the containment reference list '{@link uibk.ac.at.qe.dsl.game.LevelDefinition#getObjects <em>Objects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Objects</em>'.
   * @see uibk.ac.at.qe.dsl.game.LevelDefinition#getObjects()
   * @see #getLevelDefinition()
   * @generated
   */
  EReference getLevelDefinition_Objects();

  /**
   * Returns the meta object for the reference '{@link uibk.ac.at.qe.dsl.game.LevelDefinition#getNext <em>Next</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Next</em>'.
   * @see uibk.ac.at.qe.dsl.game.LevelDefinition#getNext()
   * @see #getLevelDefinition()
   * @generated
   */
  EReference getLevelDefinition_Next();

  /**
   * Returns the meta object for class '{@link uibk.ac.at.qe.dsl.game.Description <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Description</em>'.
   * @see uibk.ac.at.qe.dsl.game.Description
   * @generated
   */
  EClass getDescription();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.qe.dsl.game.Description#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uibk.ac.at.qe.dsl.game.Description#getName()
   * @see #getDescription()
   * @generated
   */
  EAttribute getDescription_Name();

  /**
   * Returns the meta object for class '{@link uibk.ac.at.qe.dsl.game.Person <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person</em>'.
   * @see uibk.ac.at.qe.dsl.game.Person
   * @generated
   */
  EClass getPerson();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.qe.dsl.game.Person#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uibk.ac.at.qe.dsl.game.Person#getName()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Name();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.qe.dsl.game.Person#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see uibk.ac.at.qe.dsl.game.Person#getType()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Type();

  /**
   * Returns the meta object for the attribute list '{@link uibk.ac.at.qe.dsl.game.Person#getResponse <em>Response</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Response</em>'.
   * @see uibk.ac.at.qe.dsl.game.Person#getResponse()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Response();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.qe.dsl.game.Person#getPosition <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Position</em>'.
   * @see uibk.ac.at.qe.dsl.game.Person#getPosition()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Position();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.qe.dsl.game.Person#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action</em>'.
   * @see uibk.ac.at.qe.dsl.game.Person#getAction()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Action();

  /**
   * Returns the meta object for the containment reference list '{@link uibk.ac.at.qe.dsl.game.Person#getObjects <em>Objects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Objects</em>'.
   * @see uibk.ac.at.qe.dsl.game.Person#getObjects()
   * @see #getPerson()
   * @generated
   */
  EReference getPerson_Objects();

  /**
   * Returns the meta object for the reference '{@link uibk.ac.at.qe.dsl.game.Person#getFinalObject <em>Final Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Final Object</em>'.
   * @see uibk.ac.at.qe.dsl.game.Person#getFinalObject()
   * @see #getPerson()
   * @generated
   */
  EReference getPerson_FinalObject();

  /**
   * Returns the meta object for class '{@link uibk.ac.at.qe.dsl.game.Person_O <em>Person O</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person O</em>'.
   * @see uibk.ac.at.qe.dsl.game.Person_O
   * @generated
   */
  EClass getPerson_O();

  /**
   * Returns the meta object for the reference '{@link uibk.ac.at.qe.dsl.game.Person_O#getItems <em>Items</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Items</em>'.
   * @see uibk.ac.at.qe.dsl.game.Person_O#getItems()
   * @see #getPerson_O()
   * @generated
   */
  EReference getPerson_O_Items();

  /**
   * Returns the meta object for class '{@link uibk.ac.at.qe.dsl.game.Object <em>Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object</em>'.
   * @see uibk.ac.at.qe.dsl.game.Object
   * @generated
   */
  EClass getObject();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.qe.dsl.game.Object#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uibk.ac.at.qe.dsl.game.Object#getName()
   * @see #getObject()
   * @generated
   */
  EAttribute getObject_Name();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.qe.dsl.game.Object#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see uibk.ac.at.qe.dsl.game.Object#getType()
   * @see #getObject()
   * @generated
   */
  EAttribute getObject_Type();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.qe.dsl.game.Object#getResponse <em>Response</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Response</em>'.
   * @see uibk.ac.at.qe.dsl.game.Object#getResponse()
   * @see #getObject()
   * @generated
   */
  EAttribute getObject_Response();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.qe.dsl.game.Object#getPosition <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Position</em>'.
   * @see uibk.ac.at.qe.dsl.game.Object#getPosition()
   * @see #getObject()
   * @generated
   */
  EAttribute getObject_Position();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.qe.dsl.game.Object#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action</em>'.
   * @see uibk.ac.at.qe.dsl.game.Object#getAction()
   * @see #getObject()
   * @generated
   */
  EAttribute getObject_Action();

  /**
   * Returns the meta object for enum '{@link uibk.ac.at.qe.dsl.game.Action_O <em>Action O</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Action O</em>'.
   * @see uibk.ac.at.qe.dsl.game.Action_O
   * @generated
   */
  EEnum getAction_O();

  /**
   * Returns the meta object for enum '{@link uibk.ac.at.qe.dsl.game.Action_P <em>Action P</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Action P</em>'.
   * @see uibk.ac.at.qe.dsl.game.Action_P
   * @generated
   */
  EEnum getAction_P();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GameFactory getGameFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uibk.ac.at.qe.dsl.game.impl.GameImpl <em>Game</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.qe.dsl.game.impl.GameImpl
     * @see uibk.ac.at.qe.dsl.game.impl.GamePackageImpl#getGame()
     * @generated
     */
    EClass GAME = eINSTANCE.getGame();

    /**
     * The meta object literal for the '<em><b>Scenes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__SCENES = eINSTANCE.getGame_Scenes();

    /**
     * The meta object literal for the '{@link uibk.ac.at.qe.dsl.game.impl.SceneImpl <em>Scene</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.qe.dsl.game.impl.SceneImpl
     * @see uibk.ac.at.qe.dsl.game.impl.GamePackageImpl#getScene()
     * @generated
     */
    EClass SCENE = eINSTANCE.getScene();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCENE__NAME = eINSTANCE.getScene_Name();

    /**
     * The meta object literal for the '<em><b>Declartions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENE__DECLARTIONS = eINSTANCE.getScene_Declartions();

    /**
     * The meta object literal for the '<em><b>Definitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENE__DEFINITIONS = eINSTANCE.getScene_Definitions();

    /**
     * The meta object literal for the '<em><b>Start Level</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENE__START_LEVEL = eINSTANCE.getScene_StartLevel();

    /**
     * The meta object literal for the '<em><b>Final Level</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENE__FINAL_LEVEL = eINSTANCE.getScene_FinalLevel();

    /**
     * The meta object literal for the '{@link uibk.ac.at.qe.dsl.game.impl.LevelDeclarationImpl <em>Level Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.qe.dsl.game.impl.LevelDeclarationImpl
     * @see uibk.ac.at.qe.dsl.game.impl.GamePackageImpl#getLevelDeclaration()
     * @generated
     */
    EClass LEVEL_DECLARATION = eINSTANCE.getLevelDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LEVEL_DECLARATION__NAME = eINSTANCE.getLevelDeclaration_Name();

    /**
     * The meta object literal for the '{@link uibk.ac.at.qe.dsl.game.impl.LevelDefinitionImpl <em>Level Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.qe.dsl.game.impl.LevelDefinitionImpl
     * @see uibk.ac.at.qe.dsl.game.impl.GamePackageImpl#getLevelDefinition()
     * @generated
     */
    EClass LEVEL_DEFINITION = eINSTANCE.getLevelDefinition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEVEL_DEFINITION__NAME = eINSTANCE.getLevelDefinition_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEVEL_DEFINITION__DESCRIPTION = eINSTANCE.getLevelDefinition_Description();

    /**
     * The meta object literal for the '<em><b>Persons</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEVEL_DEFINITION__PERSONS = eINSTANCE.getLevelDefinition_Persons();

    /**
     * The meta object literal for the '<em><b>Objects</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEVEL_DEFINITION__OBJECTS = eINSTANCE.getLevelDefinition_Objects();

    /**
     * The meta object literal for the '<em><b>Next</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEVEL_DEFINITION__NEXT = eINSTANCE.getLevelDefinition_Next();

    /**
     * The meta object literal for the '{@link uibk.ac.at.qe.dsl.game.impl.DescriptionImpl <em>Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.qe.dsl.game.impl.DescriptionImpl
     * @see uibk.ac.at.qe.dsl.game.impl.GamePackageImpl#getDescription()
     * @generated
     */
    EClass DESCRIPTION = eINSTANCE.getDescription();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DESCRIPTION__NAME = eINSTANCE.getDescription_Name();

    /**
     * The meta object literal for the '{@link uibk.ac.at.qe.dsl.game.impl.PersonImpl <em>Person</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.qe.dsl.game.impl.PersonImpl
     * @see uibk.ac.at.qe.dsl.game.impl.GamePackageImpl#getPerson()
     * @generated
     */
    EClass PERSON = eINSTANCE.getPerson();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__NAME = eINSTANCE.getPerson_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__TYPE = eINSTANCE.getPerson_Type();

    /**
     * The meta object literal for the '<em><b>Response</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__RESPONSE = eINSTANCE.getPerson_Response();

    /**
     * The meta object literal for the '<em><b>Position</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__POSITION = eINSTANCE.getPerson_Position();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__ACTION = eINSTANCE.getPerson_Action();

    /**
     * The meta object literal for the '<em><b>Objects</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSON__OBJECTS = eINSTANCE.getPerson_Objects();

    /**
     * The meta object literal for the '<em><b>Final Object</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSON__FINAL_OBJECT = eINSTANCE.getPerson_FinalObject();

    /**
     * The meta object literal for the '{@link uibk.ac.at.qe.dsl.game.impl.Person_OImpl <em>Person O</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.qe.dsl.game.impl.Person_OImpl
     * @see uibk.ac.at.qe.dsl.game.impl.GamePackageImpl#getPerson_O()
     * @generated
     */
    EClass PERSON_O = eINSTANCE.getPerson_O();

    /**
     * The meta object literal for the '<em><b>Items</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSON_O__ITEMS = eINSTANCE.getPerson_O_Items();

    /**
     * The meta object literal for the '{@link uibk.ac.at.qe.dsl.game.impl.ObjectImpl <em>Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.qe.dsl.game.impl.ObjectImpl
     * @see uibk.ac.at.qe.dsl.game.impl.GamePackageImpl#getObject()
     * @generated
     */
    EClass OBJECT = eINSTANCE.getObject();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT__NAME = eINSTANCE.getObject_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT__TYPE = eINSTANCE.getObject_Type();

    /**
     * The meta object literal for the '<em><b>Response</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT__RESPONSE = eINSTANCE.getObject_Response();

    /**
     * The meta object literal for the '<em><b>Position</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT__POSITION = eINSTANCE.getObject_Position();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT__ACTION = eINSTANCE.getObject_Action();

    /**
     * The meta object literal for the '{@link uibk.ac.at.qe.dsl.game.Action_O <em>Action O</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.qe.dsl.game.Action_O
     * @see uibk.ac.at.qe.dsl.game.impl.GamePackageImpl#getAction_O()
     * @generated
     */
    EEnum ACTION_O = eINSTANCE.getAction_O();

    /**
     * The meta object literal for the '{@link uibk.ac.at.qe.dsl.game.Action_P <em>Action P</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.qe.dsl.game.Action_P
     * @see uibk.ac.at.qe.dsl.game.impl.GamePackageImpl#getAction_P()
     * @generated
     */
    EEnum ACTION_P = eINSTANCE.getAction_P();

  }

} //GamePackage
