/**
 * generated by Xtext 2.13.0
 */
package uibk.ac.at.qe.dsl.game;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Level Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uibk.ac.at.qe.dsl.game.LevelDefinition#getName <em>Name</em>}</li>
 *   <li>{@link uibk.ac.at.qe.dsl.game.LevelDefinition#getPersons <em>Persons</em>}</li>
 *   <li>{@link uibk.ac.at.qe.dsl.game.LevelDefinition#getObjects <em>Objects</em>}</li>
 *   <li>{@link uibk.ac.at.qe.dsl.game.LevelDefinition#getGoalId <em>Goal Id</em>}</li>
 * </ul>
 *
 * @see uibk.ac.at.qe.dsl.game.GamePackage#getLevelDefinition()
 * @model
 * @generated
 */
public interface LevelDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(LevelDeclaration)
   * @see uibk.ac.at.qe.dsl.game.GamePackage#getLevelDefinition_Name()
   * @model
   * @generated
   */
  LevelDeclaration getName();

  /**
   * Sets the value of the '{@link uibk.ac.at.qe.dsl.game.LevelDefinition#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(LevelDeclaration value);

  /**
   * Returns the value of the '<em><b>Persons</b></em>' containment reference list.
   * The list contents are of type {@link uibk.ac.at.qe.dsl.game.Person}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Persons</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Persons</em>' containment reference list.
   * @see uibk.ac.at.qe.dsl.game.GamePackage#getLevelDefinition_Persons()
   * @model containment="true"
   * @generated
   */
  EList<Person> getPersons();

  /**
   * Returns the value of the '<em><b>Objects</b></em>' containment reference list.
   * The list contents are of type {@link uibk.ac.at.qe.dsl.game.Object}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Objects</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objects</em>' containment reference list.
   * @see uibk.ac.at.qe.dsl.game.GamePackage#getLevelDefinition_Objects()
   * @model containment="true"
   * @generated
   */
  EList<uibk.ac.at.qe.dsl.game.Object> getObjects();

  /**
   * Returns the value of the '<em><b>Goal Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Goal Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Goal Id</em>' attribute.
   * @see #setGoalId(String)
   * @see uibk.ac.at.qe.dsl.game.GamePackage#getLevelDefinition_GoalId()
   * @model
   * @generated
   */
  String getGoalId();

  /**
   * Sets the value of the '{@link uibk.ac.at.qe.dsl.game.LevelDefinition#getGoalId <em>Goal Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Goal Id</em>' attribute.
   * @see #getGoalId()
   * @generated
   */
  void setGoalId(String value);

} // LevelDefinition
