/**
 * generated by Xtext 2.13.0
 */
package uibk.ac.at.qe.dsl.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Level Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uibk.ac.at.qe.dsl.game.LevelTransition#getLevelFrom <em>Level From</em>}</li>
 *   <li>{@link uibk.ac.at.qe.dsl.game.LevelTransition#getLevelTo <em>Level To</em>}</li>
 * </ul>
 *
 * @see uibk.ac.at.qe.dsl.game.GamePackage#getLevelTransition()
 * @model
 * @generated
 */
public interface LevelTransition extends EObject
{
  /**
   * Returns the value of the '<em><b>Level From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Level From</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level From</em>' reference.
   * @see #setLevelFrom(LevelDeclaration)
   * @see uibk.ac.at.qe.dsl.game.GamePackage#getLevelTransition_LevelFrom()
   * @model
   * @generated
   */
  LevelDeclaration getLevelFrom();

  /**
   * Sets the value of the '{@link uibk.ac.at.qe.dsl.game.LevelTransition#getLevelFrom <em>Level From</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Level From</em>' reference.
   * @see #getLevelFrom()
   * @generated
   */
  void setLevelFrom(LevelDeclaration value);

  /**
   * Returns the value of the '<em><b>Level To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Level To</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level To</em>' reference.
   * @see #setLevelTo(LevelDeclaration)
   * @see uibk.ac.at.qe.dsl.game.GamePackage#getLevelTransition_LevelTo()
   * @model
   * @generated
   */
  LevelDeclaration getLevelTo();

  /**
   * Sets the value of the '{@link uibk.ac.at.qe.dsl.game.LevelTransition#getLevelTo <em>Level To</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Level To</em>' reference.
   * @see #getLevelTo()
   * @generated
   */
  void setLevelTo(LevelDeclaration value);

} // LevelTransition
