/**
 * generated by Xtext 2.13.0
 */
package uibk.ac.at.qe.dsl.game;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Level Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uibk.ac.at.qe.dsl.game.LevelDefinition#getName <em>Name</em>}</li>
 *   <li>{@link uibk.ac.at.qe.dsl.game.LevelDefinition#getDescription <em>Description</em>}</li>
 *   <li>{@link uibk.ac.at.qe.dsl.game.LevelDefinition#getPersons <em>Persons</em>}</li>
 *   <li>{@link uibk.ac.at.qe.dsl.game.LevelDefinition#getObjects <em>Objects</em>}</li>
 *   <li>{@link uibk.ac.at.qe.dsl.game.LevelDefinition#getNext <em>Next</em>}</li>
 * </ul>
 *
 * @see uibk.ac.at.qe.dsl.game.GamePackage#getLevelDefinition()
 * @model
 * @generated
 */
public interface LevelDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(LevelDeclaration)
   * @see uibk.ac.at.qe.dsl.game.GamePackage#getLevelDefinition_Name()
   * @model
   * @generated
   */
  LevelDeclaration getName();

  /**
   * Sets the value of the '{@link uibk.ac.at.qe.dsl.game.LevelDefinition#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(LevelDeclaration value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' containment reference.
   * @see #setDescription(Description)
   * @see uibk.ac.at.qe.dsl.game.GamePackage#getLevelDefinition_Description()
   * @model containment="true"
   * @generated
   */
  Description getDescription();

  /**
   * Sets the value of the '{@link uibk.ac.at.qe.dsl.game.LevelDefinition#getDescription <em>Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' containment reference.
   * @see #getDescription()
   * @generated
   */
  void setDescription(Description value);

  /**
   * Returns the value of the '<em><b>Persons</b></em>' containment reference list.
   * The list contents are of type {@link uibk.ac.at.qe.dsl.game.Person}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Persons</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Persons</em>' containment reference list.
   * @see uibk.ac.at.qe.dsl.game.GamePackage#getLevelDefinition_Persons()
   * @model containment="true"
   * @generated
   */
  EList<Person> getPersons();

  /**
   * Returns the value of the '<em><b>Objects</b></em>' containment reference list.
   * The list contents are of type {@link uibk.ac.at.qe.dsl.game.My_Object}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Objects</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objects</em>' containment reference list.
   * @see uibk.ac.at.qe.dsl.game.GamePackage#getLevelDefinition_Objects()
   * @model containment="true"
   * @generated
   */
  EList<My_Object> getObjects();

  /**
   * Returns the value of the '<em><b>Next</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Next</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Next</em>' reference.
   * @see #setNext(LevelDeclaration)
   * @see uibk.ac.at.qe.dsl.game.GamePackage#getLevelDefinition_Next()
   * @model
   * @generated
   */
  LevelDeclaration getNext();

  /**
   * Sets the value of the '{@link uibk.ac.at.qe.dsl.game.LevelDefinition#getNext <em>Next</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Next</em>' reference.
   * @see #getNext()
   * @generated
   */
  void setNext(LevelDeclaration value);

} // LevelDefinition
