/**
 * generated by Xtext 2.13.0
 */
package uibk.ac.at.qe.dsl.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uibk.ac.at.qe.dsl.game.Object#getName <em>Name</em>}</li>
 *   <li>{@link uibk.ac.at.qe.dsl.game.Object#getType <em>Type</em>}</li>
 *   <li>{@link uibk.ac.at.qe.dsl.game.Object#getPosition <em>Position</em>}</li>
 *   <li>{@link uibk.ac.at.qe.dsl.game.Object#getAction <em>Action</em>}</li>
 * </ul>
 *
 * @see uibk.ac.at.qe.dsl.game.GamePackage#getObject()
 * @model
 * @generated
 */
public interface Object extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uibk.ac.at.qe.dsl.game.GamePackage#getObject_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uibk.ac.at.qe.dsl.game.Object#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see uibk.ac.at.qe.dsl.game.GamePackage#getObject_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link uibk.ac.at.qe.dsl.game.Object#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Position</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Position</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Position</em>' attribute.
   * @see #setPosition(String)
   * @see uibk.ac.at.qe.dsl.game.GamePackage#getObject_Position()
   * @model
   * @generated
   */
  String getPosition();

  /**
   * Sets the value of the '{@link uibk.ac.at.qe.dsl.game.Object#getPosition <em>Position</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Position</em>' attribute.
   * @see #getPosition()
   * @generated
   */
  void setPosition(String value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' attribute.
   * The literals are from the enumeration {@link uibk.ac.at.qe.dsl.game.Action_O}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Action</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' attribute.
   * @see uibk.ac.at.qe.dsl.game.Action_O
   * @see #setAction(Action_O)
   * @see uibk.ac.at.qe.dsl.game.GamePackage#getObject_Action()
   * @model
   * @generated
   */
  Action_O getAction();

  /**
   * Sets the value of the '{@link uibk.ac.at.qe.dsl.game.Object#getAction <em>Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' attribute.
   * @see uibk.ac.at.qe.dsl.game.Action_O
   * @see #getAction()
   * @generated
   */
  void setAction(Action_O value);

} // Object
