/*
 * generated by Xtext 2.14.0
 */
package uibk.ac.at.qe.dsl.synthesizer


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SynthesizerRuntimeModule extends AbstractSynthesizerRuntimeModule {
}
