/*
 * generated by Xtext 2.13.0
 */
package uibk.ac.at.qe.dsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class GameGrammarAccess extends AbstractGrammarElementFinder {
	
	public class GameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.qe.dsl.Game.Game");
		private final Assignment cScenesAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cScenesSceneParserRuleCall_0 = (RuleCall)cScenesAssignment.eContents().get(0);
		
		//Game:
		//	scenes+=Scene*;
		@Override public ParserRule getRule() { return rule; }
		
		//scenes+=Scene*
		public Assignment getScenesAssignment() { return cScenesAssignment; }
		
		//Scene
		public RuleCall getScenesSceneParserRuleCall_0() { return cScenesSceneParserRuleCall_0; }
	}
	public class SceneElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.qe.dsl.Game.Scene");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNewKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDeclartionsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDeclartionsLevelDeclarationParserRuleCall_3_0 = (RuleCall)cDeclartionsAssignment_3.eContents().get(0);
		private final Assignment cDefinitionsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDefinitionsLevelDefinitionParserRuleCall_4_0 = (RuleCall)cDefinitionsAssignment_4.eContents().get(0);
		private final Keyword cStartKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cEqualsSignKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cStartLevelAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cStartLevelLevelDeclarationCrossReference_7_0 = (CrossReference)cStartLevelAssignment_7.eContents().get(0);
		private final RuleCall cStartLevelLevelDeclarationIDTerminalRuleCall_7_0_1 = (RuleCall)cStartLevelLevelDeclarationCrossReference_7_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cFinalKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cEqualsSignKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cFinalLevelAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final CrossReference cFinalLevelLevelDeclarationCrossReference_11_0 = (CrossReference)cFinalLevelAssignment_11.eContents().get(0);
		private final RuleCall cFinalLevelLevelDeclarationIDTerminalRuleCall_11_0_1 = (RuleCall)cFinalLevelLevelDeclarationCrossReference_11_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Scene:
		//	'new' name=ID
		//	'{'
		//	declartions+=LevelDeclaration*
		//	definitions+=LevelDefinition*
		//	'start' '=' startLevel=[LevelDeclaration] ';'
		//	'final' '=' finalLevel=[LevelDeclaration] ';'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'new' name=ID '{' declartions+=LevelDeclaration* definitions+=LevelDefinition* 'start' '=' startLevel=[LevelDeclaration]
		//';' 'final' '=' finalLevel=[LevelDeclaration] ';' '}'
		public Group getGroup() { return cGroup; }
		
		//'new'
		public Keyword getNewKeyword_0() { return cNewKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//declartions+=LevelDeclaration*
		public Assignment getDeclartionsAssignment_3() { return cDeclartionsAssignment_3; }
		
		//LevelDeclaration
		public RuleCall getDeclartionsLevelDeclarationParserRuleCall_3_0() { return cDeclartionsLevelDeclarationParserRuleCall_3_0; }
		
		//definitions+=LevelDefinition*
		public Assignment getDefinitionsAssignment_4() { return cDefinitionsAssignment_4; }
		
		//LevelDefinition
		public RuleCall getDefinitionsLevelDefinitionParserRuleCall_4_0() { return cDefinitionsLevelDefinitionParserRuleCall_4_0; }
		
		//'start'
		public Keyword getStartKeyword_5() { return cStartKeyword_5; }
		
		//'='
		public Keyword getEqualsSignKeyword_6() { return cEqualsSignKeyword_6; }
		
		//startLevel=[LevelDeclaration]
		public Assignment getStartLevelAssignment_7() { return cStartLevelAssignment_7; }
		
		//[LevelDeclaration]
		public CrossReference getStartLevelLevelDeclarationCrossReference_7_0() { return cStartLevelLevelDeclarationCrossReference_7_0; }
		
		//ID
		public RuleCall getStartLevelLevelDeclarationIDTerminalRuleCall_7_0_1() { return cStartLevelLevelDeclarationIDTerminalRuleCall_7_0_1; }
		
		//';'
		public Keyword getSemicolonKeyword_8() { return cSemicolonKeyword_8; }
		
		//'final'
		public Keyword getFinalKeyword_9() { return cFinalKeyword_9; }
		
		//'='
		public Keyword getEqualsSignKeyword_10() { return cEqualsSignKeyword_10; }
		
		//finalLevel=[LevelDeclaration]
		public Assignment getFinalLevelAssignment_11() { return cFinalLevelAssignment_11; }
		
		//[LevelDeclaration]
		public CrossReference getFinalLevelLevelDeclarationCrossReference_11_0() { return cFinalLevelLevelDeclarationCrossReference_11_0; }
		
		//ID
		public RuleCall getFinalLevelLevelDeclarationIDTerminalRuleCall_11_0_1() { return cFinalLevelLevelDeclarationIDTerminalRuleCall_11_0_1; }
		
		//';'
		public Keyword getSemicolonKeyword_12() { return cSemicolonKeyword_12; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}
	public class LevelDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.qe.dsl.Game.LevelDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLevelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//LevelDeclaration:
		//	'level' name=ID ';';
		@Override public ParserRule getRule() { return rule; }
		
		//'level' name=ID ';'
		public Group getGroup() { return cGroup; }
		
		//'level'
		public Keyword getLevelKeyword_0() { return cLevelKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }
	}
	public class LevelDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.qe.dsl.Game.LevelDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cNameLevelDeclarationCrossReference_0_0 = (CrossReference)cNameAssignment_0.eContents().get(0);
		private final RuleCall cNameLevelDeclarationIDTerminalRuleCall_0_0_1 = (RuleCall)cNameLevelDeclarationCrossReference_0_0.eContents().get(1);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDescriptionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDescriptionDescriptionParserRuleCall_3_0 = (RuleCall)cDescriptionAssignment_3.eContents().get(0);
		private final Assignment cPersonsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPersonsPersonParserRuleCall_4_0 = (RuleCall)cPersonsAssignment_4.eContents().get(0);
		private final Assignment cObjectsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cObjectsObjectParserRuleCall_5_0 = (RuleCall)cObjectsAssignment_5.eContents().get(0);
		private final Assignment cActionsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cActionsAction_GLOBALEnumRuleCall_6_0 = (RuleCall)cActionsAssignment_6.eContents().get(0);
		private final Keyword cGoalKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cEqualsSignKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cGoalAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cGoalIDTerminalRuleCall_9_0 = (RuleCall)cGoalAssignment_9.eContents().get(0);
		private final Keyword cSemicolonKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cNextKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cEqualsSignKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Assignment cNextAssignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final CrossReference cNextLevelDeclarationCrossReference_11_2_0 = (CrossReference)cNextAssignment_11_2.eContents().get(0);
		private final RuleCall cNextLevelDeclarationIDTerminalRuleCall_11_2_0_1 = (RuleCall)cNextLevelDeclarationCrossReference_11_2_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_11_3 = (Keyword)cGroup_11.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//LevelDefinition:
		//	name=[LevelDeclaration] '='
		//	'{'
		//	description=Description
		//	persons+=Person*
		//	objects+=Object*
		//	actions+=Action_GLOBAL*
		//	'goal' '=' goal=ID ';' ('next' '=' next=[LevelDeclaration] ';')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//name=[LevelDeclaration] '=' '{' description=Description persons+=Person* objects+=Object* actions+=Action_GLOBAL* 'goal'
		//'=' goal=ID ';' ('next' '=' next=[LevelDeclaration] ';')? '}'
		public Group getGroup() { return cGroup; }
		
		//name=[LevelDeclaration]
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//[LevelDeclaration]
		public CrossReference getNameLevelDeclarationCrossReference_0_0() { return cNameLevelDeclarationCrossReference_0_0; }
		
		//ID
		public RuleCall getNameLevelDeclarationIDTerminalRuleCall_0_0_1() { return cNameLevelDeclarationIDTerminalRuleCall_0_0_1; }
		
		//'='
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//description=Description
		public Assignment getDescriptionAssignment_3() { return cDescriptionAssignment_3; }
		
		//Description
		public RuleCall getDescriptionDescriptionParserRuleCall_3_0() { return cDescriptionDescriptionParserRuleCall_3_0; }
		
		//persons+=Person*
		public Assignment getPersonsAssignment_4() { return cPersonsAssignment_4; }
		
		//Person
		public RuleCall getPersonsPersonParserRuleCall_4_0() { return cPersonsPersonParserRuleCall_4_0; }
		
		//objects+=Object*
		public Assignment getObjectsAssignment_5() { return cObjectsAssignment_5; }
		
		//Object
		public RuleCall getObjectsObjectParserRuleCall_5_0() { return cObjectsObjectParserRuleCall_5_0; }
		
		//actions+=Action_GLOBAL*
		public Assignment getActionsAssignment_6() { return cActionsAssignment_6; }
		
		//Action_GLOBAL
		public RuleCall getActionsAction_GLOBALEnumRuleCall_6_0() { return cActionsAction_GLOBALEnumRuleCall_6_0; }
		
		//'goal'
		public Keyword getGoalKeyword_7() { return cGoalKeyword_7; }
		
		//'='
		public Keyword getEqualsSignKeyword_8() { return cEqualsSignKeyword_8; }
		
		//goal=ID
		public Assignment getGoalAssignment_9() { return cGoalAssignment_9; }
		
		//ID
		public RuleCall getGoalIDTerminalRuleCall_9_0() { return cGoalIDTerminalRuleCall_9_0; }
		
		//';'
		public Keyword getSemicolonKeyword_10() { return cSemicolonKeyword_10; }
		
		//('next' '=' next=[LevelDeclaration] ';')?
		public Group getGroup_11() { return cGroup_11; }
		
		//'next'
		public Keyword getNextKeyword_11_0() { return cNextKeyword_11_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_11_1() { return cEqualsSignKeyword_11_1; }
		
		//next=[LevelDeclaration]
		public Assignment getNextAssignment_11_2() { return cNextAssignment_11_2; }
		
		//[LevelDeclaration]
		public CrossReference getNextLevelDeclarationCrossReference_11_2_0() { return cNextLevelDeclarationCrossReference_11_2_0; }
		
		//ID
		public RuleCall getNextLevelDeclarationIDTerminalRuleCall_11_2_0_1() { return cNextLevelDeclarationIDTerminalRuleCall_11_2_0_1; }
		
		//';'
		public Keyword getSemicolonKeyword_11_3() { return cSemicolonKeyword_11_3; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class DescriptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.qe.dsl.Game.Description");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDescriptionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Description:
		//	'description' '=' name=STRING ';';
		@Override public ParserRule getRule() { return rule; }
		
		//'description' '=' name=STRING ';'
		public Group getGroup() { return cGroup; }
		
		//'description'
		public Keyword getDescriptionKeyword_0() { return cDescriptionKeyword_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }
		
		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class PersonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.qe.dsl.Game.Person");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTypeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTypeAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTypeIDTerminalRuleCall_5_0 = (RuleCall)cTypeAssignment_5.eContents().get(0);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cResponseKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cEqualsSignKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cResponseAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cResponseSTRINGTerminalRuleCall_9_0 = (RuleCall)cResponseAssignment_9.eContents().get(0);
		private final Keyword cSemicolonKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cPositionKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cEqualsSignKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cPositionAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cPositionSTRINGTerminalRuleCall_13_0 = (RuleCall)cPositionAssignment_13.eContents().get(0);
		private final Keyword cSemicolonKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cActionKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cEqualsSignKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Assignment cActionAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cActionAction_PEnumRuleCall_17_0 = (RuleCall)cActionAssignment_17.eContents().get(0);
		private final Keyword cSemicolonKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Keyword cRightCurlyBracketKeyword_19 = (Keyword)cGroup.eContents().get(19);
		
		//Person:
		//	name=ID '='
		//	'{'
		//	'type' '=' type=ID ';'
		//	'response' '=' response=STRING ';'
		//	'position' '=' position=STRING ';'
		//	'action' '=' action=Action_P ';'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID '=' '{' 'type' '=' type=ID ';' 'response' '=' response=STRING ';' 'position' '=' position=STRING ';' 'action'
		//'=' action=Action_P ';' '}'
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'type'
		public Keyword getTypeKeyword_3() { return cTypeKeyword_3; }
		
		//'='
		public Keyword getEqualsSignKeyword_4() { return cEqualsSignKeyword_4; }
		
		//type=ID
		public Assignment getTypeAssignment_5() { return cTypeAssignment_5; }
		
		//ID
		public RuleCall getTypeIDTerminalRuleCall_5_0() { return cTypeIDTerminalRuleCall_5_0; }
		
		//';'
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }
		
		//'response'
		public Keyword getResponseKeyword_7() { return cResponseKeyword_7; }
		
		//'='
		public Keyword getEqualsSignKeyword_8() { return cEqualsSignKeyword_8; }
		
		//response=STRING
		public Assignment getResponseAssignment_9() { return cResponseAssignment_9; }
		
		//STRING
		public RuleCall getResponseSTRINGTerminalRuleCall_9_0() { return cResponseSTRINGTerminalRuleCall_9_0; }
		
		//';'
		public Keyword getSemicolonKeyword_10() { return cSemicolonKeyword_10; }
		
		//'position'
		public Keyword getPositionKeyword_11() { return cPositionKeyword_11; }
		
		//'='
		public Keyword getEqualsSignKeyword_12() { return cEqualsSignKeyword_12; }
		
		//position=STRING
		public Assignment getPositionAssignment_13() { return cPositionAssignment_13; }
		
		//STRING
		public RuleCall getPositionSTRINGTerminalRuleCall_13_0() { return cPositionSTRINGTerminalRuleCall_13_0; }
		
		//';'
		public Keyword getSemicolonKeyword_14() { return cSemicolonKeyword_14; }
		
		//'action'
		public Keyword getActionKeyword_15() { return cActionKeyword_15; }
		
		//'='
		public Keyword getEqualsSignKeyword_16() { return cEqualsSignKeyword_16; }
		
		//action=Action_P
		public Assignment getActionAssignment_17() { return cActionAssignment_17; }
		
		//Action_P
		public RuleCall getActionAction_PEnumRuleCall_17_0() { return cActionAction_PEnumRuleCall_17_0; }
		
		//';'
		public Keyword getSemicolonKeyword_18() { return cSemicolonKeyword_18; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_19() { return cRightCurlyBracketKeyword_19; }
	}
	public class ObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.qe.dsl.Game.Object");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTypeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTypeAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTypeIDTerminalRuleCall_5_0 = (RuleCall)cTypeAssignment_5.eContents().get(0);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cPositionKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cEqualsSignKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cPositionAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cPositionSTRINGTerminalRuleCall_9_0 = (RuleCall)cPositionAssignment_9.eContents().get(0);
		private final Keyword cSemicolonKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cActionKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cEqualsSignKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cActionAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cActionAction_OEnumRuleCall_13_0 = (RuleCall)cActionAssignment_13.eContents().get(0);
		private final Keyword cSemicolonKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//Object:
		//	name=ID '='
		//	'{'
		//	'type' '=' type=ID ';'
		//	'position' '=' position=STRING ';'
		//	'action' '=' action=Action_O ';'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID '=' '{' 'type' '=' type=ID ';' 'position' '=' position=STRING ';' 'action' '=' action=Action_O ';' '}'
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'type'
		public Keyword getTypeKeyword_3() { return cTypeKeyword_3; }
		
		//'='
		public Keyword getEqualsSignKeyword_4() { return cEqualsSignKeyword_4; }
		
		//type=ID
		public Assignment getTypeAssignment_5() { return cTypeAssignment_5; }
		
		//ID
		public RuleCall getTypeIDTerminalRuleCall_5_0() { return cTypeIDTerminalRuleCall_5_0; }
		
		//';'
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }
		
		//'position'
		public Keyword getPositionKeyword_7() { return cPositionKeyword_7; }
		
		//'='
		public Keyword getEqualsSignKeyword_8() { return cEqualsSignKeyword_8; }
		
		//position=STRING
		public Assignment getPositionAssignment_9() { return cPositionAssignment_9; }
		
		//STRING
		public RuleCall getPositionSTRINGTerminalRuleCall_9_0() { return cPositionSTRINGTerminalRuleCall_9_0; }
		
		//';'
		public Keyword getSemicolonKeyword_10() { return cSemicolonKeyword_10; }
		
		//'action'
		public Keyword getActionKeyword_11() { return cActionKeyword_11; }
		
		//'='
		public Keyword getEqualsSignKeyword_12() { return cEqualsSignKeyword_12; }
		
		//action=Action_O
		public Assignment getActionAssignment_13() { return cActionAssignment_13; }
		
		//Action_O
		public RuleCall getActionAction_OEnumRuleCall_13_0() { return cActionAction_OEnumRuleCall_13_0; }
		
		//';'
		public Keyword getSemicolonKeyword_14() { return cSemicolonKeyword_14; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}
	
	public class Action_GLOBALElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.qe.dsl.Game.Action_GLOBAL");
		private final EnumLiteralDeclaration cLEAVEEnumLiteralDeclaration = (EnumLiteralDeclaration)rule.eContents().get(1);
		private final Keyword cLEAVELeaveKeyword_0 = (Keyword)cLEAVEEnumLiteralDeclaration.eContents().get(0);
		
		//enum Action_GLOBAL:
		//	LEAVE='Leave';
		public EnumRule getRule() { return rule; }
		
		//LEAVE='Leave'
		public EnumLiteralDeclaration getLEAVEEnumLiteralDeclaration() { return cLEAVEEnumLiteralDeclaration; }
		
		//'Leave'
		public Keyword getLEAVELeaveKeyword_0() { return cLEAVELeaveKeyword_0; }
	}
	public class Action_OElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.qe.dsl.Game.Action_O");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPICKEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPICKPickKeyword_0_0 = (Keyword)cPICKEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cUSEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cUSEUseKeyword_1_0 = (Keyword)cUSEEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum Action_O:
		//	PICK='Pick' | USE='Use';
		public EnumRule getRule() { return rule; }
		
		//PICK='Pick' | USE='Use'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PICK='Pick'
		public EnumLiteralDeclaration getPICKEnumLiteralDeclaration_0() { return cPICKEnumLiteralDeclaration_0; }
		
		//'Pick'
		public Keyword getPICKPickKeyword_0_0() { return cPICKPickKeyword_0_0; }
		
		//USE='Use'
		public EnumLiteralDeclaration getUSEEnumLiteralDeclaration_1() { return cUSEEnumLiteralDeclaration_1; }
		
		//'Use'
		public Keyword getUSEUseKeyword_1_0() { return cUSEUseKeyword_1_0; }
	}
	public class Action_PElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.qe.dsl.Game.Action_P");
		private final EnumLiteralDeclaration cTALKEnumLiteralDeclaration = (EnumLiteralDeclaration)rule.eContents().get(1);
		private final Keyword cTALKTalkKeyword_0 = (Keyword)cTALKEnumLiteralDeclaration.eContents().get(0);
		
		//enum Action_P:
		//	TALK='Talk';
		public EnumRule getRule() { return rule; }
		
		//TALK='Talk'
		public EnumLiteralDeclaration getTALKEnumLiteralDeclaration() { return cTALKEnumLiteralDeclaration; }
		
		//'Talk'
		public Keyword getTALKTalkKeyword_0() { return cTALKTalkKeyword_0; }
	}
	
	private final GameElements pGame;
	private final SceneElements pScene;
	private final LevelDeclarationElements pLevelDeclaration;
	private final LevelDefinitionElements pLevelDefinition;
	private final DescriptionElements pDescription;
	private final PersonElements pPerson;
	private final ObjectElements pObject;
	private final Action_GLOBALElements eAction_GLOBAL;
	private final Action_OElements eAction_O;
	private final Action_PElements eAction_P;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public GameGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pGame = new GameElements();
		this.pScene = new SceneElements();
		this.pLevelDeclaration = new LevelDeclarationElements();
		this.pLevelDefinition = new LevelDefinitionElements();
		this.pDescription = new DescriptionElements();
		this.pPerson = new PersonElements();
		this.pObject = new ObjectElements();
		this.eAction_GLOBAL = new Action_GLOBALElements();
		this.eAction_O = new Action_OElements();
		this.eAction_P = new Action_PElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("uibk.ac.at.qe.dsl.Game".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Game:
	//	scenes+=Scene*;
	public GameElements getGameAccess() {
		return pGame;
	}
	
	public ParserRule getGameRule() {
		return getGameAccess().getRule();
	}
	
	//Scene:
	//	'new' name=ID
	//	'{'
	//	declartions+=LevelDeclaration*
	//	definitions+=LevelDefinition*
	//	'start' '=' startLevel=[LevelDeclaration] ';'
	//	'final' '=' finalLevel=[LevelDeclaration] ';'
	//	'}';
	public SceneElements getSceneAccess() {
		return pScene;
	}
	
	public ParserRule getSceneRule() {
		return getSceneAccess().getRule();
	}
	
	//LevelDeclaration:
	//	'level' name=ID ';';
	public LevelDeclarationElements getLevelDeclarationAccess() {
		return pLevelDeclaration;
	}
	
	public ParserRule getLevelDeclarationRule() {
		return getLevelDeclarationAccess().getRule();
	}
	
	//LevelDefinition:
	//	name=[LevelDeclaration] '='
	//	'{'
	//	description=Description
	//	persons+=Person*
	//	objects+=Object*
	//	actions+=Action_GLOBAL*
	//	'goal' '=' goal=ID ';' ('next' '=' next=[LevelDeclaration] ';')?
	//	'}';
	public LevelDefinitionElements getLevelDefinitionAccess() {
		return pLevelDefinition;
	}
	
	public ParserRule getLevelDefinitionRule() {
		return getLevelDefinitionAccess().getRule();
	}
	
	//Description:
	//	'description' '=' name=STRING ';';
	public DescriptionElements getDescriptionAccess() {
		return pDescription;
	}
	
	public ParserRule getDescriptionRule() {
		return getDescriptionAccess().getRule();
	}
	
	//Person:
	//	name=ID '='
	//	'{'
	//	'type' '=' type=ID ';'
	//	'response' '=' response=STRING ';'
	//	'position' '=' position=STRING ';'
	//	'action' '=' action=Action_P ';'
	//	'}';
	public PersonElements getPersonAccess() {
		return pPerson;
	}
	
	public ParserRule getPersonRule() {
		return getPersonAccess().getRule();
	}
	
	//Object:
	//	name=ID '='
	//	'{'
	//	'type' '=' type=ID ';'
	//	'position' '=' position=STRING ';'
	//	'action' '=' action=Action_O ';'
	//	'}';
	public ObjectElements getObjectAccess() {
		return pObject;
	}
	
	public ParserRule getObjectRule() {
		return getObjectAccess().getRule();
	}
	
	//enum Action_GLOBAL:
	//	LEAVE='Leave';
	public Action_GLOBALElements getAction_GLOBALAccess() {
		return eAction_GLOBAL;
	}
	
	public EnumRule getAction_GLOBALRule() {
		return getAction_GLOBALAccess().getRule();
	}
	
	//enum Action_O:
	//	PICK='Pick' | USE='Use';
	public Action_OElements getAction_OAccess() {
		return eAction_O;
	}
	
	public EnumRule getAction_ORule() {
		return getAction_OAccess().getRule();
	}
	
	//enum Action_P:
	//	TALK='Talk';
	public Action_PElements getAction_PAccess() {
		return eAction_P;
	}
	
	public EnumRule getAction_PRule() {
		return getAction_PAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
