/*
 * generated by Xtext 2.13.0
 */
package uibk.ac.at.qe.dsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uibk.ac.at.qe.dsl.game.ui.internal.GameActivator;

public class GameUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GameActivator.getInstance().getInjector("uibk.ac.at.qe.dsl.Game");
	}

}
