/*
 * generated by Xtext 2.13.0
 */
package uibk.ac.at.qe.dsl.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import uibk.ac.at.qe.dsl.ide.contentassist.antlr.internal.InternalGameParser;
import uibk.ac.at.qe.dsl.services.GameGrammarAccess;

public class GameParser extends AbstractContentAssistParser {

	@Inject
	private GameGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalGameParser createParser() {
		InternalGameParser result = new InternalGameParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAction_OAccess().getAlternatives(), "rule__Action_O__Alternatives");
					put(grammarAccess.getSceneAccess().getGroup(), "rule__Scene__Group__0");
					put(grammarAccess.getLevelDeclarationAccess().getGroup(), "rule__LevelDeclaration__Group__0");
					put(grammarAccess.getLevelDefinitionAccess().getGroup(), "rule__LevelDefinition__Group__0");
					put(grammarAccess.getLevelDefinitionAccess().getGroup_6(), "rule__LevelDefinition__Group_6__0");
					put(grammarAccess.getDescriptionAccess().getGroup(), "rule__Description__Group__0");
					put(grammarAccess.getPersonAccess().getGroup(), "rule__Person__Group__0");
					put(grammarAccess.getPersonAccess().getGroup_19(), "rule__Person__Group_19__0");
					put(grammarAccess.getPerson_RAccess().getGroup(), "rule__Person_R__Group__0");
					put(grammarAccess.getPerson_OAccess().getGroup(), "rule__Person_O__Group__0");
					put(grammarAccess.getMy_ObjectAccess().getGroup(), "rule__My_Object__Group__0");
					put(grammarAccess.getGameAccess().getScenesAssignment(), "rule__Game__ScenesAssignment");
					put(grammarAccess.getSceneAccess().getNameAssignment_1(), "rule__Scene__NameAssignment_1");
					put(grammarAccess.getSceneAccess().getDeclartionsAssignment_3(), "rule__Scene__DeclartionsAssignment_3");
					put(grammarAccess.getSceneAccess().getDefinitionsAssignment_4(), "rule__Scene__DefinitionsAssignment_4");
					put(grammarAccess.getSceneAccess().getStartLevelAssignment_7(), "rule__Scene__StartLevelAssignment_7");
					put(grammarAccess.getSceneAccess().getFinalLevelAssignment_11(), "rule__Scene__FinalLevelAssignment_11");
					put(grammarAccess.getLevelDeclarationAccess().getNameAssignment_1(), "rule__LevelDeclaration__NameAssignment_1");
					put(grammarAccess.getLevelDefinitionAccess().getNameAssignment_0(), "rule__LevelDefinition__NameAssignment_0");
					put(grammarAccess.getLevelDefinitionAccess().getDescriptionAssignment_3(), "rule__LevelDefinition__DescriptionAssignment_3");
					put(grammarAccess.getLevelDefinitionAccess().getPersonsAssignment_4(), "rule__LevelDefinition__PersonsAssignment_4");
					put(grammarAccess.getLevelDefinitionAccess().getObjectsAssignment_5(), "rule__LevelDefinition__ObjectsAssignment_5");
					put(grammarAccess.getLevelDefinitionAccess().getNextAssignment_6_2(), "rule__LevelDefinition__NextAssignment_6_2");
					put(grammarAccess.getDescriptionAccess().getNameAssignment_2(), "rule__Description__NameAssignment_2");
					put(grammarAccess.getPersonAccess().getNameAssignment_0(), "rule__Person__NameAssignment_0");
					put(grammarAccess.getPersonAccess().getTypeAssignment_5(), "rule__Person__TypeAssignment_5");
					put(grammarAccess.getPersonAccess().getResponseAssignment_9(), "rule__Person__ResponseAssignment_9");
					put(grammarAccess.getPersonAccess().getPositionAssignment_13(), "rule__Person__PositionAssignment_13");
					put(grammarAccess.getPersonAccess().getActionAssignment_17(), "rule__Person__ActionAssignment_17");
					put(grammarAccess.getPersonAccess().getFinalObjectAssignment_19_2(), "rule__Person__FinalObjectAssignment_19_2");
					put(grammarAccess.getPerson_RAccess().getItemAssignment_0(), "rule__Person_R__ItemAssignment_0");
					put(grammarAccess.getPerson_OAccess().getItemsAssignment_0(), "rule__Person_O__ItemsAssignment_0");
					put(grammarAccess.getMy_ObjectAccess().getNameAssignment_0(), "rule__My_Object__NameAssignment_0");
					put(grammarAccess.getMy_ObjectAccess().getTypeAssignment_5(), "rule__My_Object__TypeAssignment_5");
					put(grammarAccess.getMy_ObjectAccess().getResponseAssignment_9(), "rule__My_Object__ResponseAssignment_9");
					put(grammarAccess.getMy_ObjectAccess().getPositionAssignment_13(), "rule__My_Object__PositionAssignment_13");
					put(grammarAccess.getMy_ObjectAccess().getActionAssignment_17(), "rule__My_Object__ActionAssignment_17");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GameGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GameGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
