/*
 * generated by Xtext 2.13.0
 */
package uibk.ac.at.qe.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractGameValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(uibk.ac.at.qe.dsl.game.GamePackage.eINSTANCE);
		return result;
	}
	
}
