/*
 * generated by Xtext 2.13.0
 */
package uibk.ac.at.qe.dsl.oscilloscope


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class OscilloscopeStandaloneSetup extends OscilloscopeStandaloneSetupGenerated {

	def static void doSetup() {
		new OscilloscopeStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
