/*
 * generated by Xtext 2.13.0
 */
package uibk.ac.at.qe.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGameScopeProvider extends DelegatingScopeProvider {
}
